#!/bin/sh
'''exec' "/Users/srisaisasanksadineni/Desktop/Smart home security system /venv/bin/python" "$0" "$@"
' '''
import sys
from face_recognition.face_recognition_cli import main
if __name__ == '__main__':
    sys.argv[0] = sys.argv[0].removesuffix('.exe')
    sys.exit(main())
